### ISSUE TITLE
Ratpack?

### ISSUE THREAD

**Issue by bsideup** [threepointone/ratpack#1]
Hi!

Looks like your name & color choice is... errr.... a bit conflicting with some popular project in JVM world:
https://github.com/ratpack/ratpack

:)

**Comment by threepointone** [comment]
Why is this an issue? :)

**Comment by threepointone** [comment]
Those are the colors from the js logo.

**Comment by donaldpipowitch** [comment]
Call it `ratpack.js` and we have no conflicts XD

**Comment by threepointone** [comment]
that's not a bad idea :)

**Comment by threepointone** [comment]
Picked up ratpack on npm. Closing this issue.
