### ISSUE TITLE
linting

### ISSUE THREAD

**Issue by threepointone** [threepointone/ratpack#18]

**Comment by threepointone** [comment]
multiple issues - 
- should we have a default eslint config, overridable with pragmas, that is run in a loader? CRA does this with some success 
- how should this integrate with editors? Ideally I'd like for it to *just work*, syntax checking and all. bonus if you can do reason checking too.

**Comment by yatharthx** [comment]
@threepointone I guess having a default eslint config (overridable, as you say) makes sense. We can have a wrapper around of eslint to solve the purpose ( something like [XO](https://github.com/sindresorhus/xo) ). What do you think?

I'm not really sure about the integration with editors. Maybe we can come back to it later.

**Comment by threepointone** [comment]
don't want to make wrapper, provides no utility beyond what already exists out there.

**Comment by threepointone** [comment]
some options 
- letting user manually edit the `eslintConfig` field in `.ratpack/package.json`
- pragma `// @ratpack { lint: { ... } }`

**Comment by threepointone** [comment]
not going to bikeshed on this too much. copied CRA's setup, shows errors in-browser. closing for now.
