### ISSUE TITLE
refs doesn't bind correctly, componentDidMount

### ISSUE THREAD

**Issue by OlegLustenko** [threepointone/ratpack#4]
Nice idea 👍 to use electron.
I have problems with refs - refs does not initialize correctly.
Also, componentDidMount lifecycle seems to have problems

**Comment by threepointone** [comment]
I'll have a look, thank you for the catch!

**Comment by threepointone** [comment]
refs and componentDidMount appear to be working fine, do you have a code sample that failed?

**Comment by OlegLustenko** [comment]
Hi, I have download last version of ratpack and this bug has gone, refs and componenDidMount works correctly

**Comment by threepointone** [comment]
Fantastic! 👍🏽
