### ISSUE TITLE
Option to run relative to directory

### ISSUE THREAD

**Issue by rreusser** [threepointone/ratpack#5]
Drag and drop is nice, but perhaps there's a way of running this from the command line or relative to a given directory? Perhaps the window would list js files in that directory? Perhaps drag-and-dropping a folder lists all the js files in it? The ability to quickly switch between files with common setup would be awesome.

I usually use `budo`, which is *great*; it's just the lack of multiple entry points that's the main hangup (ref: https://github.com/mattdesl/budo/issues/139 ). I've been meaning to invest a bit of time to better understand and improve my setup; it's just never *quite* worthwhile.

**Comment by threepointone** [comment]
CLI support is on the cards! And as for listing, (once I get support in) you could right click open js files from finder/explorer, or set them as the default app to open .js files. How does that sound?

**Comment by rreusser** [comment]
Cool. Related thought: Maybe two options in the UI? 1. open in $EDITOR and 2. open as webpage?

**Comment by threepointone** [comment]
Ooh that's a good one. Will put on todo list

**Comment by threepointone** [comment]
tracking cli support here #11

**Comment by threepointone** [comment]
closing this one for now, will track 'open in editor' etc in #24.
